cini9/food-truckr

.gitignore, app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_card-category.scss, app/assets/stylesheets/components/_index.scss, app/controllers/food_trucks_controller.rb, app/uploaders/photo_uploader.rb, app/views/food_trucks/index.html.erb, app/views/layouts/application.html.erb, db/schema.rb
Banner is done for index. Not cards for displaying trucks yet, I'm on it !
=> index: banner done

app/assets/stylesheets/components/_card_trip.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_text_box.scss, app/controllers/food_trucks_controller.rb, app/views/food_trucks/index.html.erb, app/views/food_trucks/show.html.erb, db/schema.rb
Created the base of the view for the show of a food truck.
=> Food truck show

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/food_trucks_controller.rb, app/policies/application_policy.rb, app/policies/food_truck_policy.rb, app/views/devise/registrations/edit.html.erb, app/views/food_trucks/show.html.erb, test/policies/food_truck_policy_test.rb
DONT FORGET TO BUNDLE INSTALL !!!
=> pundit implemented

app/policies/food_truck_policy.rb, app/views/shared/_navbar.html.erb
- Modified navbar
- Changed pundit to allow anyone to create a food truck
=> improved navbar with access to add new food trucks and access profile

app/controllers/food_trucks_controller.rb
Allowed access to index and show page without being logged in
=> access resolved

Gemfile, Gemfile.lock, app/controllers/food_trucks_controller.rb, app/models/food_truck.rb, app/views/food_trucks/show.html.erb, app/views/shared/_form.html.erb, config/initializers/money.rb, config/routes.rb, db/migrate/20191120114126_remove_price_from_food_trucks.rb, db/migrate/20191120114140_add_price_to_food_trucks.rb, db/schema.rb
- monetize gem added => **YOU GUYS NEED TO BUNDLE INSTALL**
- price column in food trucks table modified to work with monetize => **YOU GUYS NEED TO DB:MIGRATE** => **@FOODTRUCK.PRICE HAS BECOME @FOODTRUCK.PRICE_CENTS**
- monetize initializers added
=> monetize implemented

app/controllers/reservations_controller.rb, app/views/reservations/index.html.erb, config/routes.rb
Need to add the payment path I will take care of the other ones
=> reservation index done, need to add links for the buttons

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/payments_controller.rb, app/controllers/reservations_controller.rb, app/models/food_truck.rb, app/models/reservation.rb, app/views/payments/new.html.erb, app/views/reservations/index.html.erb, app/views/reservations/show.html.erb, config/initializers/stripe.rb, config/routes.rb, db/migrate/20191120125753_add_stripe_columns_to_reservations.rb, db/schema.rb, test/controllers/payments_controller_test.rb
- stripe implemented => **YOU NEED TO BUNDLE INSTALL AND DB:MIGRATE**
- merged with reservation index view
=> Implement stripe

app/views/devise/registrations/edit.html.erb
=> edit ux improved

app/controllers/reservations_controller.rb, app/models/reservation.rb
=> currency issues corrected

app/controllers/payments_controller.rb, app/controllers/reservations_controller.rb, config/routes.rb, db/schema.rb
- render conflict corrected
- successful payment redirected to paid action in payments controller
=> render issue corrected and payment redirect corrected

app/controllers/food_trucks_controller.rb
Fixed the mandotary sign in sign up on the landing page
=> fixed login on home

app/views/food_trucks/show.html.erb
=> corrected back button on FT show

app/views/layouts/application.html.erb
Transformed alert from blue to red
=> alert in red

app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/users/registrations/new.html.erb
- buttons and CTA clarified for sign up and login
=> sign up and login pages cta improved

app/controllers/users/registrations_controller.rb, app/views/users/registrations/edit.html.erb
- user can complete/update profile without password
=> Remove password confirmation

app/views/users/registrations/edit.html.erb
Edit user --> Your Profile
added avatar label to the upload avatar button
=> corrected profile title and avatar

app/views/food_trucks/home.html.erb
added food truck count on index and capitalized the category title
=> food truck count on index

app/views/food_trucks/show.html.erb
- checkin/checkout date order changed to dd/mm/yyy
- checkout date default = today + 1
=> checkin checkout fields improved

app/controllers/food_trucks_controller.rb, app/controllers/reservations_controller.rb, app/views/layouts/application.html.erb
=> corrected alert and notice

app/assets/stylesheets/components/_text_box.scss, app/views/food_trucks/show.html.erb
- food truck photo size standardized
- back button moved next to the "Reserve" button
- edit functionality moved inside of the description text box
=> food truck show improved

app/views/shared/_navbar.html.erb
=> generic avatar photo changed

app/views/food_trucks/edit.html.erb, app/views/food_trucks/new.html.erb
wrapped edit and new foodtruck form in card
=> modified edit and new foodtruck

app/controllers/food_trucks_controller.rb, app/views/food_trucks/edit.html.erb
Modified edit foodtruck to look like show
=> modified edit foodtruck to look like show
